// Paramètres ajustables — spec section « Paramètres ajustables ».
// RIEN n'est hardcodé dans la logique : toujours passer par config.get(cle).
// Chaque entrée : valeur par défaut, section (pour l'écran Réglages) et aide.

import { etat, sauvegarder } from './etat.js';

export const DEFAUTS = {
  // --- Tirage et paquets
  dureeBaseSecondes:  { valeur: 86400, section: 'Tirage et paquets',
    aide: "Temps de chargement d'un paquet à vitesse x1, en secondes (24h = 86400)." },
  tailleDuPaquet:     { valeur: 10, section: 'Tirage et paquets',
    aide: 'Nombre de cartes tirées par paquet.' },

  // --- Rareté et PV (utilisés à la génération des données, informatif ici)
  seuilLegendaire: { valeur: 0.02, section: 'Rareté et PV',
    aide: 'Fraction de la collection en Légendaire. ⚠️ N’agit qu’à la régénération des données de cartes, jamais sur les cartes existantes.' },
  seuilMythique:   { valeur: 0.06, section: 'Rareté et PV',
    aide: 'Fraction de la collection en Mythique. ⚠️ Régénération des données uniquement.' },
  seuilEpique:     { valeur: 0.16, section: 'Rareté et PV',
    aide: 'Fraction de la collection en Épique. ⚠️ Régénération des données uniquement.' },
  seuilRare:       { valeur: 0.26, section: 'Rareté et PV',
    aide: 'Fraction de la collection en Rare. ⚠️ Régénération des données uniquement.' },
  pvMin: { valeur: 20,  section: 'Rareté et PV',
    aide: 'PV de la carte la moins populaire. ⚠️ Régénération des données uniquement.' },
  pvMax: { valeur: 340, section: 'Rareté et PV',
    aide: 'PV de la carte la plus populaire. ⚠️ Régénération des données uniquement.' },

  // --- Module 1 — Calibrage 3D
  vitesseDeriveCible: { valeur: 0.25, section: 'Module 1 — Calibrage 3D',
    aide: "Vitesse max de la cible cachée (% de l'espace par seconde). Plus c'est haut, plus le calibrage se périme vite entre deux visites." },
  inertieCible: { valeur: 0.5, section: 'Module 1 — Calibrage 3D',
    aide: 'Résistance de la cible aux changements de direction (0 = nerveuse, 1 = très inerte).' },
  amplitudeBruitSignal: { valeur: 15, section: 'Module 1 — Calibrage 3D',
    aide: 'Écart maximal entre le signal affiché et la proximité réelle (points sur 100).' },
  vitesseDeriveBruit: { valeur: 3, section: 'Module 1 — Calibrage 3D',
    aide: 'Durée (s) sur laquelle le bruit du signal dérive.' },
  frequenceRafraichissementBoost: { valeur: 10, section: 'Module 1 — Calibrage 3D',
    aide: 'Intervalle (s) entre deux mises à jour du boost affiché.' },
  dureeMoyenneFenetreStabilite: { valeur: 18000, section: 'Module 1 — Calibrage 3D',
    aide: 'Intervalle moyen (s) entre deux fenêtres de stabilité (5h = 18000).' },
  dureeFenetreStabilite: { valeur: 600, section: 'Module 1 — Calibrage 3D',
    aide: "Durée de base (s) d'une fenêtre de stabilité normale (jackpot ×2-4, turbulence ×1-2)." },
  probabiliteEvenementRadical: { valeur: 0.12, section: 'Module 1 — Calibrage 3D',
    aide: "Chance qu'une fenêtre soit radicale (jackpot ou turbulence) plutôt que normale." },
  energieMax: { valeur: 10000, section: 'Module 1 — Calibrage 3D',
    aide: "Capacité maximale de la jauge d'énergie." },
  tauxEnergieParSeconde: { valeur: 0.5, section: 'Module 1 — Calibrage 3D',
    aide: "Vitesse de génération/consommation d'énergie à ±100% (points par seconde)." },

  // --- Module 2 — Chaîne Collecte/Traitement/Raffinage
  dureeDeVieLot: { valeur: 2700, section: 'Module 2 — Chaîne',
    aide: "Temps (s) avant péremption d'un lot collecté non traité (45 min = 2700)." },
  capaciteMaxFileAttente: { valeur: 600, section: 'Module 2 — Chaîne',
    aide: 'Stockage maximum de la file de matière collectée en attente.' },
  capaciteMaxStockTraite: { valeur: 2000, section: 'Module 2 — Chaîne',
    aide: 'Stockage maximum du stock de matière traitée impérissable.' },
  debitMaxCollecte: { valeur: 40, section: 'Module 2 — Chaîne',
    aide: 'Débit maximal de Collecte à 100% de capacité (unités/min).' },
  debitMaxTraitement: { valeur: 40, section: 'Module 2 — Chaîne',
    aide: 'Débit maximal de Traitement à 100% de capacité (unités/min).' },
  intensiteBoostParRaffinage: { valeur: 1.5, section: 'Module 2 — Chaîne',
    aide: 'Constante K : boost = 1 + raffinage% × K (à 1.5 : raffinage 100% = ×2.5).' },
  consommationStockParRaffinage: { valeur: 20, section: 'Module 2 — Chaîne',
    aide: 'Consommation du stock traité à Raffinage 100% (unités/min).' },

  // --- Module 3 — Marché à 3 indices
  capitalDepart: { valeur: 500, section: 'Module 3 — Marché',
    aide: 'Liquidités de départ du joueur.' },
  allocationSecoursJournaliere: { valeur: 20, section: 'Module 3 — Marché',
    aide: 'Filet de sécurité passif quotidien (unités/jour).' },
  tauxCommission: { valeur: 0.0015, section: 'Module 3 — Marché',
    aide: 'Commission prélevée à chaque achat/vente (0.0015 = 0,15%).' },
  tauxDividendeIndiceStable: { valeur: 0.005, section: 'Module 3 — Marché',
    aide: "Dividende journalier de l'indice Stable, proportionnel aux parts détenues." },
  amplitudeTauxIntensiteMin: { valeur: 0.5, section: 'Module 3 — Marché',
    aide: 'Borne basse du taux de conversion Intensité.' },
  amplitudeTauxIntensiteMax: { valeur: 2, section: 'Module 3 — Marché',
    aide: 'Borne haute du taux de conversion Intensité.' },
  amplitudeTauxDureeMin: { valeur: 0.5, section: 'Module 3 — Marché',
    aide: 'Borne basse du taux de conversion Durée.' },
  amplitudeTauxDureeMax: { valeur: 2, section: 'Module 3 — Marché',
    aide: 'Borne haute du taux de conversion Durée.' },
  vitesseDeriveTauxConversion: { valeur: 21600, section: 'Module 3 — Marché',
    aide: 'Durée caractéristique (s) de dérive des taux de conversion (6h = 21600).' },
  echelleIntensiteM3: { valeur: 0.08, section: 'Module 3 — Marché',
    aide: 'Intensité de boost obtenue par unité de capital engagée (à taux ×1).' },
  echelleDureeM3: { valeur: 1080, section: 'Module 3 — Marché',
    aide: 'Secondes de durée de boost par unité de capital engagée (à taux ×1).' },

  // --- Station : horloge de simulation partagée (replay hors-ligne)
  pasFinStation: { valeur: 1, section: 'Station — horloge',
    aide: '⚠️ avancé — Pas de simulation (s) quand l’app est ouverte.' },
  pasGrosStation: { valeur: 60, section: 'Station — horloge',
    aide: '⚠️ avancé — Pas de simulation (s) pour rejouer les longues absences.' },
  seuilGrosStation: { valeur: 300, section: 'Station — horloge',
    aide: '⚠️ avancé — Retard (s) au-delà duquel le replay passe en gros pas.' },
  maxRattrapageStation: { valeur: 604800, section: 'Station — horloge',
    aide: '⚠️ avancé — Absence maximale rejouée (s), au-delà on saute (7j = 604800).' },

  // --- Module 1 : constantes fines du moteur
  porteeProximiteM1: { valeur: 100, section: 'Module 1 — Calibrage 3D',
    aide: 'Distance à laquelle la proximité tombe à 0 (plus petit = jeu plus dur).' },
  facteurAccelerationCibleM1: { valeur: 3, section: 'Module 1 — Calibrage 3D',
    aide: "Facteur de l'accélération aléatoire de la cible dans la formule d'inertie." },
  amortissementRebondM1: { valeur: 0.5, section: 'Module 1 — Calibrage 3D',
    aide: 'Perte de vitesse de la cible au rebond sur un bord (0-1).' },
  amortissementBruitM1: { valeur: 0.8, section: 'Module 1 — Calibrage 3D',
    aide: 'Gain des impulsions de la marche aléatoire du bruit du signal.' },
  decroissanceBruitM1: { valeur: 0.02, section: 'Module 1 — Calibrage 3D',
    aide: 'Rappel du bruit du signal vers 0 (par seconde).' },
  variationIntervalleFenetre: { valeur: 0.4, section: 'Module 1 — Calibrage 3D',
    aide: "Variation aléatoire (±fraction) de l'intervalle entre fenêtres de stabilité." },
  probaJackpot: { valeur: 0.5, section: 'Module 1 — Calibrage 3D',
    aide: 'Part des événements radicaux qui sont des jackpots (le reste : turbulences).' },
  agitationFenetreNormale: { valeur: 0.15, section: 'Module 1 — Calibrage 3D',
    aide: "Facteur de vitesse de la cible pendant une fenêtre normale (0.15 = très calme)." },
  agitationJackpot: { valeur: 0.03, section: 'Module 1 — Calibrage 3D',
    aide: 'Facteur de vitesse de la cible pendant un jackpot (quasi immobile).' },
  agitationTurbulence: { valeur: 3, section: 'Module 1 — Calibrage 3D',
    aide: 'Facteur de vitesse de la cible pendant une turbulence.' },
  dureeNormaleMin: { valeur: 0.8, section: 'Module 1 — Calibrage 3D',
    aide: 'Durée min d’une fenêtre normale (× dureeFenetreStabilite).' },
  dureeNormaleMax: { valeur: 1.4, section: 'Module 1 — Calibrage 3D',
    aide: 'Durée max d’une fenêtre normale (× dureeFenetreStabilite).' },
  dureeJackpotMin: { valeur: 2, section: 'Module 1 — Calibrage 3D',
    aide: 'Durée min d’un jackpot (× dureeFenetreStabilite).' },
  dureeJackpotMax: { valeur: 4, section: 'Module 1 — Calibrage 3D',
    aide: 'Durée max d’un jackpot (× dureeFenetreStabilite).' },
  dureeTurbulenceMin: { valeur: 1, section: 'Module 1 — Calibrage 3D',
    aide: 'Durée min d’une turbulence (× dureeFenetreStabilite).' },
  dureeTurbulenceMax: { valeur: 2, section: 'Module 1 — Calibrage 3D',
    aide: 'Durée max d’une turbulence (× dureeFenetreStabilite).' },

  // --- Module 2 : flux et bruit
  niveauFluxFaible: { valeur: 0.22, section: 'Module 2 — Chaîne',
    aide: 'Niveau du régime Faible (fraction du débit max de collecte).' },
  niveauFluxModere: { valeur: 0.55, section: 'Module 2 — Chaîne',
    aide: 'Niveau du régime Modéré (fraction du débit max de collecte).' },
  niveauFluxFort: { valeur: 1.0, section: 'Module 2 — Chaîne',
    aide: 'Niveau du régime Fort (fraction du débit max de collecte).' },
  dureeRegimeFluxMin: { valeur: 7200, section: 'Module 2 — Chaîne',
    aide: 'Durée minimale (s) d’un régime de flux (2h = 7200).' },
  dureeRegimeFluxMax: { valeur: 18000, section: 'Module 2 — Chaîne',
    aide: 'Durée maximale (s) d’un régime de flux (5h = 18000).' },
  amplitudeBruitFlux: { valeur: 0.12, section: 'Module 2 — Chaîne',
    aide: 'Amplitude maximale (±) du bruit autour du niveau de régime.' },
  incrementBruitFlux: { valeur: 0.01, section: 'Module 2 — Chaîne',
    aide: 'Taille des pas de la marche aléatoire du bruit de flux (par s).' },
  rappelBruitFlux: { valeur: 0.02, section: 'Module 2 — Chaîne',
    aide: 'Rappel du bruit de flux vers 0 (par seconde).' },
  granulariteLotsM2: { valeur: 60, section: 'Module 2 — Chaîne',
    aide: '⚠️ avancé — Regroupement des lots collectés par tranche d’expiration (s).' },
  transFaibleVersModere: { valeur: 2, section: 'Module 2 — Chaîne',
    aide: 'Poids de transition Faible→Modéré (normalisé avec Faible→Fort).' },
  transFaibleVersFort: { valeur: 1, section: 'Module 2 — Chaîne',
    aide: 'Poids de transition Faible→Fort.' },
  transModereVersFaible: { valeur: 1, section: 'Module 2 — Chaîne',
    aide: 'Poids de transition Modéré→Faible.' },
  transModereVersFort: { valeur: 2, section: 'Module 2 — Chaîne',
    aide: 'Poids de transition Modéré→Fort.' },
  transFortVersModere: { valeur: 2, section: 'Module 2 — Chaîne',
    aide: 'Poids de transition Fort→Modéré.' },
  transFortVersFaible: { valeur: 1, section: 'Module 2 — Chaîne',
    aide: 'Poids de transition Fort→Faible.' },

  // --- Module 3 : profils des 3 indices
  deriveHoraireStable: { valeur: 0.003, section: 'Module 3 — indice Stable',
    aide: 'Dérive de tendance par heure (fraction du prix) en régime directionnel.' },
  volatiliteHoraireStable: { valeur: 0.0025, section: 'Module 3 — indice Stable',
    aide: 'Écart-type du bruit de prix par √heure.' },
  facteurAgiteStable: { valeur: 1.3, section: 'Module 3 — indice Stable',
    aide: 'Multiplicateur de volatilité pendant les grappes agitées.' },
  probaChocStable: { valeur: 0.00005, section: 'Module 3 — indice Stable',
    aide: 'Probabilité de choc par seconde.' },
  amplitudeChocStable: { valeur: 0.012, section: 'Module 3 — indice Stable',
    aide: 'Amplitude de base d’un choc (fraction du prix, ×0.5-1.5 aléatoire).' },
  deriveHoraireModere: { valeur: 0.010, section: 'Module 3 — indice Modéré',
    aide: 'Dérive de tendance par heure.' },
  volatiliteHoraireModere: { valeur: 0.010, section: 'Module 3 — indice Modéré',
    aide: 'Écart-type du bruit de prix par √heure.' },
  facteurAgiteModere: { valeur: 1.8, section: 'Module 3 — indice Modéré',
    aide: 'Multiplicateur de volatilité pendant les grappes agitées.' },
  probaChocModere: { valeur: 0.0001, section: 'Module 3 — indice Modéré',
    aide: 'Probabilité de choc par seconde.' },
  amplitudeChocModere: { valeur: 0.035, section: 'Module 3 — indice Modéré',
    aide: 'Amplitude de base d’un choc.' },
  deriveHoraireVolatil: { valeur: 0.025, section: 'Module 3 — indice Volatil',
    aide: 'Dérive de tendance par heure.' },
  volatiliteHoraireVolatil: { valeur: 0.030, section: 'Module 3 — indice Volatil',
    aide: 'Écart-type du bruit de prix par √heure.' },
  facteurAgiteVolatil: { valeur: 2.5, section: 'Module 3 — indice Volatil',
    aide: 'Multiplicateur de volatilité pendant les grappes agitées.' },
  probaChocVolatil: { valeur: 0.0003, section: 'Module 3 — indice Volatil',
    aide: 'Probabilité de choc par seconde.' },
  amplitudeChocVolatil: { valeur: 0.09, section: 'Module 3 — indice Volatil',
    aide: 'Amplitude de base d’un choc.' },

  // --- Module 3 : dynamique commune des indices
  dureeCalmeMin: { valeur: 3600, section: 'Module 3 — Marché',
    aide: 'Durée minimale (s) d’une phase calme (1h = 3600).' },
  dureeCalmeMax: { valeur: 10800, section: 'Module 3 — Marché',
    aide: 'Durée maximale (s) d’une phase calme.' },
  dureeAgiteMin: { valeur: 1080, section: 'Module 3 — Marché',
    aide: 'Durée minimale (s) d’une grappe agitée (18 min = 1080).' },
  dureeAgiteMax: { valeur: 3600, section: 'Module 3 — Marché',
    aide: 'Durée maximale (s) d’une grappe agitée.' },
  poidsRegimeBaissier: { valeur: 2, section: 'Module 3 — Marché',
    aide: 'Poids du tirage d’un régime baissier (normalisé avec stable/haussier).' },
  poidsRegimeStable: { valeur: 1, section: 'Module 3 — Marché',
    aide: 'Poids du tirage d’un régime sans tendance.' },
  poidsRegimeHaussier: { valeur: 2, section: 'Module 3 — Marché',
    aide: 'Poids du tirage d’un régime haussier.' },
  dureeRegimeIndiceMin: { valeur: 7200, section: 'Module 3 — Marché',
    aide: 'Durée minimale (s) d’un régime de tendance (2h = 7200).' },
  dureeRegimeIndiceMax: { valeur: 21600, section: 'Module 3 — Marché',
    aide: 'Durée maximale (s) d’un régime de tendance (6h = 21600).' },
  meanReversionHoraire: { valeur: 0.1, section: 'Module 3 — Marché',
    aide: 'Rappel du prix vers sa moyenne mobile (fraction de l’écart par heure).' },
  periodeMoyenneMobile: { valeur: 10800, section: 'Module 3 — Marché',
    aide: 'Période (s) de la moyenne mobile affichée (3h = 10800).' },
  prixPlancherM3: { valeur: 5, section: 'Module 3 — Marché',
    aide: 'Prix minimal absolu d’un indice.' },
  echantillonnageIndices: { valeur: 300, section: 'Module 3 — Marché',
    aide: '⚠️ avancé — Intervalle (s) entre deux points de courbe conservés.' },
  maxPointsIndices: { valeur: 600, section: 'Module 3 — Marché',
    aide: '⚠️ avancé — Plafond de points d’historique par indice.' },
  dureeMinConversionM3: { valeur: 30, section: 'Module 3 — Marché',
    aide: 'Durée minimale (s) d’une instance de boost pour valider une conversion.' },

  // --- Module 3 : calendrier d'événements
  fenetreResolutionMin: { valeur: 7200, section: 'Module 3 — événements',
    aide: 'Délai minimal (s) avant résolution d’une échéance (2h = 7200).' },
  fenetreResolutionMax: { valeur: 21600, section: 'Module 3 — événements',
    aide: 'Délai maximal (s) avant résolution d’une échéance (6h = 21600).' },
  nbEcheances: { valeur: 4, section: 'Module 3 — événements',
    aide: 'Nombre d’échéances maintenues en permanence au calendrier.' },
  poidsImpactFaible: { valeur: 3, section: 'Module 3 — événements',
    aide: 'Poids du tirage d’un impact faible (normalisé).' },
  poidsImpactMoyen: { valeur: 2, section: 'Module 3 — événements',
    aide: 'Poids du tirage d’un impact moyen.' },
  poidsImpactFort: { valeur: 1, section: 'Module 3 — événements',
    aide: 'Poids du tirage d’un impact fort.' },
  retournementFaible: { valeur: 0.15, section: 'Module 3 — événements',
    aide: 'Probabilité qu’une échéance faible parte dans la direction inverse.' },
  retournementMoyen: { valeur: 0.08, section: 'Module 3 — événements',
    aide: 'Probabilité de retournement d’une échéance moyenne.' },
  retournementFort: { valeur: 0.02, section: 'Module 3 — événements',
    aide: 'Probabilité de retournement d’une échéance forte.' },
  fausseAlerteFaible: { valeur: 0.08, section: 'Module 3 — événements',
    aide: 'Probabilité qu’une échéance faible soit sans effet.' },
  fausseAlerteMoyen: { valeur: 0.05, section: 'Module 3 — événements',
    aide: 'Probabilité de fausse alerte d’une échéance moyenne.' },
  fausseAlerteFort: { valeur: 0.03, section: 'Module 3 — événements',
    aide: 'Probabilité de fausse alerte d’une échéance forte.' },
  sautFaibleMin: { valeur: 0.01, section: 'Module 3 — événements',
    aide: 'Saut de prix minimal d’un impact faible (fraction).' },
  sautFaibleMax: { valeur: 0.02, section: 'Module 3 — événements',
    aide: 'Saut de prix maximal d’un impact faible.' },
  sautMoyenMin: { valeur: 0.03, section: 'Module 3 — événements',
    aide: 'Saut de prix minimal d’un impact moyen.' },
  sautMoyenMax: { valeur: 0.06, section: 'Module 3 — événements',
    aide: 'Saut de prix maximal d’un impact moyen.' },
  sautFortMin: { valeur: 0.08, section: 'Module 3 — événements',
    aide: 'Saut de prix minimal d’un impact fort.' },
  sautFortMax: { valeur: 0.14, section: 'Module 3 — événements',
    aide: 'Saut de prix maximal d’un impact fort.' },
  dureeRegimePostEvenementMin: { valeur: 3600, section: 'Module 3 — événements',
    aide: 'Durée min (s) du régime imposé à l’indice après une résolution.' },
  dureeRegimePostEvenementMax: { valeur: 10800, section: 'Module 3 — événements',
    aide: 'Durée max (s) du régime imposé après une résolution.' },

  // --- Éclats
};

export const config = {
  get(cle) {
    const surcharge = etat.configUtilisateur?.[cle];
    if (surcharge !== undefined && surcharge !== null) return surcharge;
    if (!(cle in DEFAUTS)) throw new Error(`Paramètre inconnu : ${cle}`);
    return DEFAUTS[cle].valeur;
  },
  set(cle, valeur) {
    if (!(cle in DEFAUTS)) throw new Error(`Paramètre inconnu : ${cle}`);
    // Revenir à la valeur par défaut = plus de surcharge à stocker.
    if (valeur === DEFAUTS[cle].valeur) delete etat.configUtilisateur[cle];
    else etat.configUtilisateur[cle] = valeur;
    sauvegarder();
  },
  estSurcharge(cle) {
    return etat.configUtilisateur?.[cle] !== undefined
        && etat.configUtilisateur[cle] !== null;
  },
  sections() {
    const s = {};
    for (const [cle, def] of Object.entries(DEFAUTS)) {
      (s[def.section] ??= []).push(cle);
    }
    return s;
  },
  reinitialiserSection(section) {
    for (const [cle, def] of Object.entries(DEFAUTS)) {
      if (def.section === section) delete etat.configUtilisateur[cle];
    }
    sauvegarder();
  },
};
